defaults:
  - combustion
    #- data: fakedata
    #- model: fakemodel
    #- optimizer: adam
    #- trainer: local
    #- schedule: one_cycle
    #- sweeper: no_sweep
  - data: fakedata
  - model: fakemodel2
  - model/criterion: celoss
  - trainer: trainer


    #datamodule: 0
