defaults:
  - combustion
    #- data: fakedata
    #- model: fakemodel
    #- optimizer: adam
    #- trainer: local
    #- schedule: one_cycle
    #- sweeper: no_sweep

  - data: fakedata
  - model: base_fakemodel
  - trainer: local


    #datamodule: 0
