repos:
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
        - id: black
          args: [--line-length=120, --target-version=py37]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
        - id: flake8
          args: [--append-config=tox.ini]
