# @package _group_
# https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#trainer-flags
_target_: pytorch_lightning.Trainer
params:
  max_epochs: 100
  gpus: 1
  amp_level: O1
  #amp_backend: apex
  precision: 16
  accumulate_grad_batches: 1
  #limit_train_batches: 10
  #check_val_every_n_epoch: 5
  #gradient_clip_val: 1.0
  #auto_lr_find: True
  #track_grad_norm: 2
  # gradient_clip_val: 1.0
  terminate_on_nan: true
  #num_sanity_val_steps: -1
  #accelerator: ddp
  #sync_batchnorm: true
  #limit_val_batches: 8
  #default_save_path: /path/to/outputs
  #resume_from_checkpoint: /app/outputs/checkpoints/fcos_d0.ckpt
  default_root_dir: /mnt/iscsi/fcos


  #weights_summary: full
  
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: ${trainer.params.default_root_dir}
      name: ${now:%Y-%m-%d}
      version: ${now:%H-%M-%S}
              
