# @package _global_
# https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#trainer-flags
trainer:
  catch_exceptions: true
  test_only: false
  load_from_checkpoint: 
  preprocess_train_path: 
  _target_: pytorch_lightning.Trainer
  params:
    max_epochs: 2
    fast_dev_run: true
    auto_lr_find: false
    deterministic: false
    limit_train_batches: 10
    callbacks:
      - _target_: pytorch_lightning.callbacks.ModelCheckpoint
        params:
          dirpath: ${trainer.params.default_root_dir}
          filename: "{epoch}-{step}"
          mode: "min"

    resume_from_checkpoint:
    default_root_dir:
