# @package _group_
batch_size: 1

train:
  num_workers: 4
  pin_memory: true
  drop_last: true
  shuffle: true
  #collate_fn: 
  #  _target_: medcog_classifier.preprocessing.Collate

  _target_: torchvision.datasets.CocoDetection
  params:
    root: /mnt/iscsi/coco/val2017
    annFile: /mnt/iscsi/coco/annotations_trainval2017/annotations/instances_val2017.json
    transforms:
      _target_: efficientdet_fcos.preprocessing.TrainingTransform
      params:
        
        resize:
          _target_: albumentations.augmentations.transforms.Resize
          params:
            height: 256
            width: 256

        flip: 
          _target_: albumentations.augmentations.transforms.HorizontalFlip

        random_brightness:
          _target_: albumentations.augmentations.transforms.RandomBrightnessContrast
          params:
            p: 0.8
            brightness_limit: 0.1
            contrast_limit: 0.3

validate:
  num_workers: 4
  pin_memory: true
  drop_last: true
  shuffle: true
  #collate_fn: 
  #  _target_: medcog_classifier.preprocessing.Collate

  _target_: torchvision.datasets.CocoDetection
  params:
    root: /mnt/iscsi/coco/val2017
    annFile: /mnt/iscsi/coco/annotations_trainval2017/annotations/instances_val2017.json
    transforms:
      _target_: efficientdet_fcos.preprocessing.TrainingTransform
      params:
        
        resize:
          _target_: albumentations.augmentations.transforms.Resize
          params:
            height: 256
            width: 256

