# @package _global_
dataset:
  num_workers: 4

  train:
    _target_: torchvision.datasets.FakeData
    params:
      size: 10000
      image_size: [1, 128, 128]
      transform:
        _target_: torchvision.transforms.ToTensor

  validate:
    _target_: torchvision.datasets.FakeData
    params:
      size: 100
      image_size: ${dataset.train.params.image_size}
      transform:
        _target_: torchvision.transforms.ToTensor

  test:
    _target_: torchvision.datasets.FakeData
    params:
      size: 100
      image_size: ${dataset.train.params.image_size}
      transform:
        _target_: torchvision.transforms.ToTensor
