version: 2.1


orbs:
  codecov: codecov/codecov@1.0.2


jobs:

    check_code_quality:
        working_directory: ~/combustion
        docker:
            - image: circleci/python:3.8
        parallelism: 1
        steps:
            - checkout
            - run: 
                name: Run quality tests
                command: make quality


    run_tests:
        working_directory: ~/combustion
        docker:
            - image: circleci/python:3.8
        parallelism: 1
        steps:
            - checkout
            - run: 
                name: Install dependencies
                command: make venv
            - save_cache:
                paths:
                  - ~/.cache/pip
                key: v1-dependencies-{{ checksum "setup.py" }}
            - run: 
                name: Run tests
                command: make ci-test
            - codecov/upload:
                file: coverage.xml


workflow_filters: &workflow_filters
    filters:
        branches:
            only:
                - master
                - feat/circleci


workflows:
    version: 2
    build_and_test:
        jobs:
            - check_code_quality
            - run_tests
