# https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#trainer-flags
trainer:
  cls: pytorch_lightning.Trainer
  params:
    max_epochs: 2
    gpus: 1
    amp_level: O1
    precision: 16
    #default_save_path: /path/to/outputs
